kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  selector:
    deployment: prometheus-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
